-- -------------------------------------------------------------
--
-- Module: butterworth_filter
-- Generated by MATLAB(R) 8.1 and the Filter Design HDL Coder 2.9.3.
-- Generated on: 2013-09-04 13:43:24
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- HDLSynthTool: ISE
-- HDLSynthCmd: xfile add $src_dir/%s\n
-- HDLSynthFilePostfix: _ise.tcl
-- HDLSynthInit: set src_dir [pwd]\nset prj_dir "synprj"\nfile mkdir ../$prj_dir\ncd ../$prj_dir\nproject new %s.xise\nproject set family Virtex4\nproject set device xc4vsx35\nproject set package ff668\nproject set speed -10\n
-- HDLSynthTerm: process run "Synthesize - XST"
-- TargetDirectory: /home/MQCO/matlab_iirFilter
-- Name: butterworth_filter
-- TestBenchName: butterworth_filter_tb
-- TestBenchStimulus: impulse step 

-- Filter Specifications:
--
-- Sampling Frequency : N/A (normalized frequency)
-- Response           : Lowpass
-- Specification      : N,F3dB
-- Filter Order       : 35
-- 3-dB Point         : 0.5
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Multipliers           : 53
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time IIR Filter (real)
-- -------------------------------
-- Filter Structure    : Direct-Form II, Second-Order Sections
-- Number of Sections  : 18
-- Stable              : Yes
-- Linear Phase        : No
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY butterworth_filter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    real; -- double
         filter_out                      :   OUT   real  -- double
         );

END butterworth_filter;


----------------------------------------------------------------
--Module Architecture: butterworth_filter
----------------------------------------------------------------
ARCHITECTURE rtl OF butterworth_filter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF real; -- double
  -- Constants
  CONSTANT scaleconst1                    : real := 4.7853079697616757E-01; -- double
  CONSTANT coeff_b1_section1              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section1              : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section1              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section1              : real := -2.1251036351806704E-16; -- double
  CONSTANT coeff_a3_section1              : real := 9.1412318790467040E-01; -- double
  CONSTANT scaleconst2                    : real := 4.4082642880303446E-01; -- double
  CONSTANT coeff_b1_section2              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section2              : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section2              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section2              : real := -1.9576626044816451E-16; -- double
  CONSTANT coeff_a3_section2              : real := 7.6330571521213808E-01; -- double
  CONSTANT scaleconst3                    : real := 4.0899095149389642E-01; -- double
  CONSTANT coeff_b1_section3              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section3              : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section3              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section3              : real := -1.8162846848474977E-16; -- double
  CONSTANT coeff_a3_section3              : real := 6.3596380597558588E-01; -- double
  CONSTANT scaleconst4                    : real := 3.8196601125010521E-01; -- double
  CONSTANT coeff_b1_section4              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section4              : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section4              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section4              : real := -1.6962698412563937E-16; -- double
  CONSTANT coeff_a3_section4              : real := 5.2786404500042072E-01; -- double
  CONSTANT scaleconst5                    : real := 3.5893109501869858E-01; -- double
  CONSTANT coeff_b1_section5              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section5              : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section5              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section5              : real := -1.5939742637747162E-16; -- double
  CONSTANT coeff_a3_section5              : real := 4.3572438007479425E-01; -- double
  CONSTANT scaleconst6                    : real := 3.3924325330389471E-01; -- double
  CONSTANT coeff_b1_section6              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section6              : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section6              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section6              : real := -1.5065426830669127E-16; -- double
  CONSTANT coeff_a3_section6              : real := 3.5697301321557895E-01; -- double
  CONSTANT scaleconst7                    : real := 3.2239407644719947E-01; -- double
  CONSTANT coeff_b1_section7              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section7              : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section7              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section7              : real := -1.4317173066977752E-16; -- double
  CONSTANT coeff_a3_section7              : real := 2.8957630578879795E-01; -- double
  CONSTANT scaleconst8                    : real := 3.0797852836990408E-01; -- double
  CONSTANT coeff_b1_section8              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section8              : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section8              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section8              : real := -1.3676994131457582E-16; -- double
  CONSTANT coeff_a3_section8              : real := 2.3191411347961657E-01; -- double
  CONSTANT scaleconst9                    : real := 2.9567207359204334E-01; -- double
  CONSTANT coeff_b1_section9              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section9              : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section9              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section9              : real := -1.3130477753622012E-16; -- double
  CONSTANT coeff_a3_section9              : real := 1.8268829436817347E-01; -- double
  CONSTANT scaleconst10                   : real := 2.8521370046586003E-01; -- double
  CONSTANT coeff_b1_section10             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section10             : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section10             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section10             : real := -1.2666032687829624E-16; -- double
  CONSTANT coeff_a3_section10             : real := 1.4085480186344015E-01; -- double
  CONSTANT scaleconst11                   : real := 2.7639320225002101E-01; -- double
  CONSTANT coeff_b1_section11             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section11             : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section11             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section11             : real := -1.2274323879514043E-16; -- double
  CONSTANT coeff_a3_section11             : real := 1.0557280900008419E-01; -- double
  CONSTANT scaleconst12                   : real := 2.6904158011851814E-01; -- double
  CONSTANT coeff_b1_section12             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section12             : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section12             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section12             : real := -1.1947846273164509E-16; -- double
  CONSTANT coeff_a3_section12             : real := 7.6166320474072902E-02; -- double
  CONSTANT scaleconst13                   : real := 2.6302377090042173E-01; -- double
  CONSTANT coeff_b1_section13             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section13             : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section13             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section13             : real := -1.1680601859095220E-16; -- double
  CONSTANT coeff_a3_section13             : real := 5.2095083601687082E-02; -- double
  CONSTANT scaleconst14                   : real := 2.5823313461697889E-01; -- double
  CONSTANT coeff_b1_section14             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section14             : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section14             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section14             : real := -1.1467854870915903E-16; -- double
  CONSTANT coeff_a3_section14             : real := 3.2932538467915634E-02; -- double
  CONSTANT scaleconst15                   : real := 2.5458729897918969E-01; -- double
  CONSTANT coeff_b1_section15             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section15             : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section15             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section15             : real := -1.1305947244153003E-16; -- double
  CONSTANT coeff_a3_section15             : real := 1.8349195916759042E-02; -- double
  CONSTANT scaleconst16                   : real := 2.5202507330574186E-01; -- double
  CONSTANT coeff_b1_section16             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section16             : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section16             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section16             : real := -1.1192161566675104E-16; -- double
  CONSTANT coeff_a3_section16             : real := 8.1002932229675764E-03; -- double
  CONSTANT scaleconst17                   : real := 2.5050422818781681E-01; -- double
  CONSTANT coeff_b1_section17             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section17             : real := 2.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section17             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section17             : real := -1.1124622476002738E-16; -- double
  CONSTANT coeff_a3_section17             : real := 2.0169127512673943E-03; -- double
  CONSTANT scaleconst18                   : real := 4.9999999999999994E-01; -- double
  CONSTANT coeff_b1_section18             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section18             : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b3_section18             : real := 0.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section18             : real := -5.5511151231257827E-17; -- double
  CONSTANT coeff_a3_section18             : real := 0.0000000000000000E+00; -- double
  -- Signals
  SIGNAL input_register                   : real := 0.0; -- double
  SIGNAL scale1                           : real := 0.0; -- double
  SIGNAL scaletypeconvert1                : real := 0.0; -- double
  -- Section 1 Signals 
  SIGNAL a1sum1                           : real := 0.0; -- double
  SIGNAL a2sum1                           : real := 0.0; -- double
  SIGNAL b1sum1                           : real := 0.0; -- double
  SIGNAL b2sum1                           : real := 0.0; -- double
  SIGNAL delay_section1                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv1                       : real := 0.0; -- double
  SIGNAL a2mul1                           : real := 0.0; -- double
  SIGNAL a3mul1                           : real := 0.0; -- double
  SIGNAL b1mul1                           : real := 0.0; -- double
  SIGNAL b2mul1                           : real := 0.0; -- double
  SIGNAL b3mul1                           : real := 0.0; -- double
  SIGNAL scale2                           : real := 0.0; -- double
  SIGNAL scaletypeconvert2                : real := 0.0; -- double
  -- Section 2 Signals 
  SIGNAL a1sum2                           : real := 0.0; -- double
  SIGNAL a2sum2                           : real := 0.0; -- double
  SIGNAL b1sum2                           : real := 0.0; -- double
  SIGNAL b2sum2                           : real := 0.0; -- double
  SIGNAL delay_section2                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv2                       : real := 0.0; -- double
  SIGNAL a2mul2                           : real := 0.0; -- double
  SIGNAL a3mul2                           : real := 0.0; -- double
  SIGNAL b1mul2                           : real := 0.0; -- double
  SIGNAL b2mul2                           : real := 0.0; -- double
  SIGNAL b3mul2                           : real := 0.0; -- double
  SIGNAL scale3                           : real := 0.0; -- double
  SIGNAL scaletypeconvert3                : real := 0.0; -- double
  -- Section 3 Signals 
  SIGNAL a1sum3                           : real := 0.0; -- double
  SIGNAL a2sum3                           : real := 0.0; -- double
  SIGNAL b1sum3                           : real := 0.0; -- double
  SIGNAL b2sum3                           : real := 0.0; -- double
  SIGNAL delay_section3                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv3                       : real := 0.0; -- double
  SIGNAL a2mul3                           : real := 0.0; -- double
  SIGNAL a3mul3                           : real := 0.0; -- double
  SIGNAL b1mul3                           : real := 0.0; -- double
  SIGNAL b2mul3                           : real := 0.0; -- double
  SIGNAL b3mul3                           : real := 0.0; -- double
  SIGNAL scale4                           : real := 0.0; -- double
  SIGNAL scaletypeconvert4                : real := 0.0; -- double
  -- Section 4 Signals 
  SIGNAL a1sum4                           : real := 0.0; -- double
  SIGNAL a2sum4                           : real := 0.0; -- double
  SIGNAL b1sum4                           : real := 0.0; -- double
  SIGNAL b2sum4                           : real := 0.0; -- double
  SIGNAL delay_section4                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv4                       : real := 0.0; -- double
  SIGNAL a2mul4                           : real := 0.0; -- double
  SIGNAL a3mul4                           : real := 0.0; -- double
  SIGNAL b1mul4                           : real := 0.0; -- double
  SIGNAL b2mul4                           : real := 0.0; -- double
  SIGNAL b3mul4                           : real := 0.0; -- double
  SIGNAL scale5                           : real := 0.0; -- double
  SIGNAL scaletypeconvert5                : real := 0.0; -- double
  -- Section 5 Signals 
  SIGNAL a1sum5                           : real := 0.0; -- double
  SIGNAL a2sum5                           : real := 0.0; -- double
  SIGNAL b1sum5                           : real := 0.0; -- double
  SIGNAL b2sum5                           : real := 0.0; -- double
  SIGNAL delay_section5                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv5                       : real := 0.0; -- double
  SIGNAL a2mul5                           : real := 0.0; -- double
  SIGNAL a3mul5                           : real := 0.0; -- double
  SIGNAL b1mul5                           : real := 0.0; -- double
  SIGNAL b2mul5                           : real := 0.0; -- double
  SIGNAL b3mul5                           : real := 0.0; -- double
  SIGNAL scale6                           : real := 0.0; -- double
  SIGNAL scaletypeconvert6                : real := 0.0; -- double
  -- Section 6 Signals 
  SIGNAL a1sum6                           : real := 0.0; -- double
  SIGNAL a2sum6                           : real := 0.0; -- double
  SIGNAL b1sum6                           : real := 0.0; -- double
  SIGNAL b2sum6                           : real := 0.0; -- double
  SIGNAL delay_section6                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv6                       : real := 0.0; -- double
  SIGNAL a2mul6                           : real := 0.0; -- double
  SIGNAL a3mul6                           : real := 0.0; -- double
  SIGNAL b1mul6                           : real := 0.0; -- double
  SIGNAL b2mul6                           : real := 0.0; -- double
  SIGNAL b3mul6                           : real := 0.0; -- double
  SIGNAL scale7                           : real := 0.0; -- double
  SIGNAL scaletypeconvert7                : real := 0.0; -- double
  -- Section 7 Signals 
  SIGNAL a1sum7                           : real := 0.0; -- double
  SIGNAL a2sum7                           : real := 0.0; -- double
  SIGNAL b1sum7                           : real := 0.0; -- double
  SIGNAL b2sum7                           : real := 0.0; -- double
  SIGNAL delay_section7                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv7                       : real := 0.0; -- double
  SIGNAL a2mul7                           : real := 0.0; -- double
  SIGNAL a3mul7                           : real := 0.0; -- double
  SIGNAL b1mul7                           : real := 0.0; -- double
  SIGNAL b2mul7                           : real := 0.0; -- double
  SIGNAL b3mul7                           : real := 0.0; -- double
  SIGNAL scale8                           : real := 0.0; -- double
  SIGNAL scaletypeconvert8                : real := 0.0; -- double
  -- Section 8 Signals 
  SIGNAL a1sum8                           : real := 0.0; -- double
  SIGNAL a2sum8                           : real := 0.0; -- double
  SIGNAL b1sum8                           : real := 0.0; -- double
  SIGNAL b2sum8                           : real := 0.0; -- double
  SIGNAL delay_section8                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv8                       : real := 0.0; -- double
  SIGNAL a2mul8                           : real := 0.0; -- double
  SIGNAL a3mul8                           : real := 0.0; -- double
  SIGNAL b1mul8                           : real := 0.0; -- double
  SIGNAL b2mul8                           : real := 0.0; -- double
  SIGNAL b3mul8                           : real := 0.0; -- double
  SIGNAL scale9                           : real := 0.0; -- double
  SIGNAL scaletypeconvert9                : real := 0.0; -- double
  -- Section 9 Signals 
  SIGNAL a1sum9                           : real := 0.0; -- double
  SIGNAL a2sum9                           : real := 0.0; -- double
  SIGNAL b1sum9                           : real := 0.0; -- double
  SIGNAL b2sum9                           : real := 0.0; -- double
  SIGNAL delay_section9                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv9                       : real := 0.0; -- double
  SIGNAL a2mul9                           : real := 0.0; -- double
  SIGNAL a3mul9                           : real := 0.0; -- double
  SIGNAL b1mul9                           : real := 0.0; -- double
  SIGNAL b2mul9                           : real := 0.0; -- double
  SIGNAL b3mul9                           : real := 0.0; -- double
  SIGNAL scale10                          : real := 0.0; -- double
  SIGNAL scaletypeconvert10               : real := 0.0; -- double
  -- Section 10 Signals 
  SIGNAL a1sum10                          : real := 0.0; -- double
  SIGNAL a2sum10                          : real := 0.0; -- double
  SIGNAL b1sum10                          : real := 0.0; -- double
  SIGNAL b2sum10                          : real := 0.0; -- double
  SIGNAL delay_section10                  : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv10                      : real := 0.0; -- double
  SIGNAL a2mul10                          : real := 0.0; -- double
  SIGNAL a3mul10                          : real := 0.0; -- double
  SIGNAL b1mul10                          : real := 0.0; -- double
  SIGNAL b2mul10                          : real := 0.0; -- double
  SIGNAL b3mul10                          : real := 0.0; -- double
  SIGNAL scale11                          : real := 0.0; -- double
  SIGNAL scaletypeconvert11               : real := 0.0; -- double
  -- Section 11 Signals 
  SIGNAL a1sum11                          : real := 0.0; -- double
  SIGNAL a2sum11                          : real := 0.0; -- double
  SIGNAL b1sum11                          : real := 0.0; -- double
  SIGNAL b2sum11                          : real := 0.0; -- double
  SIGNAL delay_section11                  : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv11                      : real := 0.0; -- double
  SIGNAL a2mul11                          : real := 0.0; -- double
  SIGNAL a3mul11                          : real := 0.0; -- double
  SIGNAL b1mul11                          : real := 0.0; -- double
  SIGNAL b2mul11                          : real := 0.0; -- double
  SIGNAL b3mul11                          : real := 0.0; -- double
  SIGNAL scale12                          : real := 0.0; -- double
  SIGNAL scaletypeconvert12               : real := 0.0; -- double
  -- Section 12 Signals 
  SIGNAL a1sum12                          : real := 0.0; -- double
  SIGNAL a2sum12                          : real := 0.0; -- double
  SIGNAL b1sum12                          : real := 0.0; -- double
  SIGNAL b2sum12                          : real := 0.0; -- double
  SIGNAL delay_section12                  : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv12                      : real := 0.0; -- double
  SIGNAL a2mul12                          : real := 0.0; -- double
  SIGNAL a3mul12                          : real := 0.0; -- double
  SIGNAL b1mul12                          : real := 0.0; -- double
  SIGNAL b2mul12                          : real := 0.0; -- double
  SIGNAL b3mul12                          : real := 0.0; -- double
  SIGNAL scale13                          : real := 0.0; -- double
  SIGNAL scaletypeconvert13               : real := 0.0; -- double
  -- Section 13 Signals 
  SIGNAL a1sum13                          : real := 0.0; -- double
  SIGNAL a2sum13                          : real := 0.0; -- double
  SIGNAL b1sum13                          : real := 0.0; -- double
  SIGNAL b2sum13                          : real := 0.0; -- double
  SIGNAL delay_section13                  : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv13                      : real := 0.0; -- double
  SIGNAL a2mul13                          : real := 0.0; -- double
  SIGNAL a3mul13                          : real := 0.0; -- double
  SIGNAL b1mul13                          : real := 0.0; -- double
  SIGNAL b2mul13                          : real := 0.0; -- double
  SIGNAL b3mul13                          : real := 0.0; -- double
  SIGNAL scale14                          : real := 0.0; -- double
  SIGNAL scaletypeconvert14               : real := 0.0; -- double
  -- Section 14 Signals 
  SIGNAL a1sum14                          : real := 0.0; -- double
  SIGNAL a2sum14                          : real := 0.0; -- double
  SIGNAL b1sum14                          : real := 0.0; -- double
  SIGNAL b2sum14                          : real := 0.0; -- double
  SIGNAL delay_section14                  : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv14                      : real := 0.0; -- double
  SIGNAL a2mul14                          : real := 0.0; -- double
  SIGNAL a3mul14                          : real := 0.0; -- double
  SIGNAL b1mul14                          : real := 0.0; -- double
  SIGNAL b2mul14                          : real := 0.0; -- double
  SIGNAL b3mul14                          : real := 0.0; -- double
  SIGNAL scale15                          : real := 0.0; -- double
  SIGNAL scaletypeconvert15               : real := 0.0; -- double
  -- Section 15 Signals 
  SIGNAL a1sum15                          : real := 0.0; -- double
  SIGNAL a2sum15                          : real := 0.0; -- double
  SIGNAL b1sum15                          : real := 0.0; -- double
  SIGNAL b2sum15                          : real := 0.0; -- double
  SIGNAL delay_section15                  : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv15                      : real := 0.0; -- double
  SIGNAL a2mul15                          : real := 0.0; -- double
  SIGNAL a3mul15                          : real := 0.0; -- double
  SIGNAL b1mul15                          : real := 0.0; -- double
  SIGNAL b2mul15                          : real := 0.0; -- double
  SIGNAL b3mul15                          : real := 0.0; -- double
  SIGNAL scale16                          : real := 0.0; -- double
  SIGNAL scaletypeconvert16               : real := 0.0; -- double
  -- Section 16 Signals 
  SIGNAL a1sum16                          : real := 0.0; -- double
  SIGNAL a2sum16                          : real := 0.0; -- double
  SIGNAL b1sum16                          : real := 0.0; -- double
  SIGNAL b2sum16                          : real := 0.0; -- double
  SIGNAL delay_section16                  : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv16                      : real := 0.0; -- double
  SIGNAL a2mul16                          : real := 0.0; -- double
  SIGNAL a3mul16                          : real := 0.0; -- double
  SIGNAL b1mul16                          : real := 0.0; -- double
  SIGNAL b2mul16                          : real := 0.0; -- double
  SIGNAL b3mul16                          : real := 0.0; -- double
  SIGNAL scale17                          : real := 0.0; -- double
  SIGNAL scaletypeconvert17               : real := 0.0; -- double
  -- Section 17 Signals 
  SIGNAL a1sum17                          : real := 0.0; -- double
  SIGNAL a2sum17                          : real := 0.0; -- double
  SIGNAL b1sum17                          : real := 0.0; -- double
  SIGNAL b2sum17                          : real := 0.0; -- double
  SIGNAL delay_section17                  : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv17                      : real := 0.0; -- double
  SIGNAL a2mul17                          : real := 0.0; -- double
  SIGNAL a3mul17                          : real := 0.0; -- double
  SIGNAL b1mul17                          : real := 0.0; -- double
  SIGNAL b2mul17                          : real := 0.0; -- double
  SIGNAL b3mul17                          : real := 0.0; -- double
  SIGNAL scale18                          : real := 0.0; -- double
  SIGNAL scaletypeconvert18               : real := 0.0; -- double
  --   -- Section 18 Signals 
  SIGNAL a1sum18                          : real := 0.0; -- double
  SIGNAL b1sum18                          : real := 0.0; -- double
  SIGNAL delay_section18                  : real := 0.0; -- double
  SIGNAL inputconv18                      : real := 0.0; -- double
  SIGNAL a2mul18                          : real := 0.0; -- double
  SIGNAL b1mul18                          : real := 0.0; -- double
  SIGNAL b2mul18                          : real := 0.0; -- double
  SIGNAL output_typeconvert               : real := 0.0; -- double
  SIGNAL output_register                  : real := 0.0; -- double


BEGIN

  -- Block Statements
  input_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_register <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        input_register <= filter_in;
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  scale1 <= input_register * scaleconst1;

  scaletypeconvert1 <= scale1;


  --   ------------------ Section 1 ------------------

  delay_process_section1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section1(0) <= 0.0000000000000000E+00;
      delay_section1(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section1(1) <= delay_section1(0);
        delay_section1(0) <= a1sum1;
      END IF;
    END IF;
  END PROCESS delay_process_section1;

  inputconv1 <= scaletypeconvert1;


  a2mul1 <= delay_section1(0) * coeff_a2_section1;

  a3mul1 <= delay_section1(1) * coeff_a3_section1;

  b1mul1 <= a1sum1;


  b2mul1 <= delay_section1(0) * coeff_b2_section1;

  b3mul1 <= delay_section1(1);


  a2sum1 <= inputconv1 - a2mul1;

  a1sum1 <= a2sum1 - a3mul1;

  b2sum1 <= b1mul1 + b2mul1;

  b1sum1 <= b2sum1 + b3mul1;

  scale2 <= b1sum1 * scaleconst2;

  scaletypeconvert2 <= scale2;


  --   ------------------ Section 2 ------------------

  delay_process_section2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section2(0) <= 0.0000000000000000E+00;
      delay_section2(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section2(1) <= delay_section2(0);
        delay_section2(0) <= a1sum2;
      END IF;
    END IF;
  END PROCESS delay_process_section2;

  inputconv2 <= scaletypeconvert2;


  a2mul2 <= delay_section2(0) * coeff_a2_section2;

  a3mul2 <= delay_section2(1) * coeff_a3_section2;

  b1mul2 <= a1sum2;


  b2mul2 <= delay_section2(0) * coeff_b2_section2;

  b3mul2 <= delay_section2(1);


  a2sum2 <= inputconv2 - a2mul2;

  a1sum2 <= a2sum2 - a3mul2;

  b2sum2 <= b1mul2 + b2mul2;

  b1sum2 <= b2sum2 + b3mul2;

  scale3 <= b1sum2 * scaleconst3;

  scaletypeconvert3 <= scale3;


  --   ------------------ Section 3 ------------------

  delay_process_section3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section3(0) <= 0.0000000000000000E+00;
      delay_section3(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section3(1) <= delay_section3(0);
        delay_section3(0) <= a1sum3;
      END IF;
    END IF;
  END PROCESS delay_process_section3;

  inputconv3 <= scaletypeconvert3;


  a2mul3 <= delay_section3(0) * coeff_a2_section3;

  a3mul3 <= delay_section3(1) * coeff_a3_section3;

  b1mul3 <= a1sum3;


  b2mul3 <= delay_section3(0) * coeff_b2_section3;

  b3mul3 <= delay_section3(1);


  a2sum3 <= inputconv3 - a2mul3;

  a1sum3 <= a2sum3 - a3mul3;

  b2sum3 <= b1mul3 + b2mul3;

  b1sum3 <= b2sum3 + b3mul3;

  scale4 <= b1sum3 * scaleconst4;

  scaletypeconvert4 <= scale4;


  --   ------------------ Section 4 ------------------

  delay_process_section4 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section4(0) <= 0.0000000000000000E+00;
      delay_section4(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section4(1) <= delay_section4(0);
        delay_section4(0) <= a1sum4;
      END IF;
    END IF;
  END PROCESS delay_process_section4;

  inputconv4 <= scaletypeconvert4;


  a2mul4 <= delay_section4(0) * coeff_a2_section4;

  a3mul4 <= delay_section4(1) * coeff_a3_section4;

  b1mul4 <= a1sum4;


  b2mul4 <= delay_section4(0) * coeff_b2_section4;

  b3mul4 <= delay_section4(1);


  a2sum4 <= inputconv4 - a2mul4;

  a1sum4 <= a2sum4 - a3mul4;

  b2sum4 <= b1mul4 + b2mul4;

  b1sum4 <= b2sum4 + b3mul4;

  scale5 <= b1sum4 * scaleconst5;

  scaletypeconvert5 <= scale5;


  --   ------------------ Section 5 ------------------

  delay_process_section5 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section5(0) <= 0.0000000000000000E+00;
      delay_section5(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section5(1) <= delay_section5(0);
        delay_section5(0) <= a1sum5;
      END IF;
    END IF;
  END PROCESS delay_process_section5;

  inputconv5 <= scaletypeconvert5;


  a2mul5 <= delay_section5(0) * coeff_a2_section5;

  a3mul5 <= delay_section5(1) * coeff_a3_section5;

  b1mul5 <= a1sum5;


  b2mul5 <= delay_section5(0) * coeff_b2_section5;

  b3mul5 <= delay_section5(1);


  a2sum5 <= inputconv5 - a2mul5;

  a1sum5 <= a2sum5 - a3mul5;

  b2sum5 <= b1mul5 + b2mul5;

  b1sum5 <= b2sum5 + b3mul5;

  scale6 <= b1sum5 * scaleconst6;

  scaletypeconvert6 <= scale6;


  --   ------------------ Section 6 ------------------

  delay_process_section6 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section6(0) <= 0.0000000000000000E+00;
      delay_section6(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section6(1) <= delay_section6(0);
        delay_section6(0) <= a1sum6;
      END IF;
    END IF;
  END PROCESS delay_process_section6;

  inputconv6 <= scaletypeconvert6;


  a2mul6 <= delay_section6(0) * coeff_a2_section6;

  a3mul6 <= delay_section6(1) * coeff_a3_section6;

  b1mul6 <= a1sum6;


  b2mul6 <= delay_section6(0) * coeff_b2_section6;

  b3mul6 <= delay_section6(1);


  a2sum6 <= inputconv6 - a2mul6;

  a1sum6 <= a2sum6 - a3mul6;

  b2sum6 <= b1mul6 + b2mul6;

  b1sum6 <= b2sum6 + b3mul6;

  scale7 <= b1sum6 * scaleconst7;

  scaletypeconvert7 <= scale7;


  --   ------------------ Section 7 ------------------

  delay_process_section7 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section7(0) <= 0.0000000000000000E+00;
      delay_section7(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section7(1) <= delay_section7(0);
        delay_section7(0) <= a1sum7;
      END IF;
    END IF;
  END PROCESS delay_process_section7;

  inputconv7 <= scaletypeconvert7;


  a2mul7 <= delay_section7(0) * coeff_a2_section7;

  a3mul7 <= delay_section7(1) * coeff_a3_section7;

  b1mul7 <= a1sum7;


  b2mul7 <= delay_section7(0) * coeff_b2_section7;

  b3mul7 <= delay_section7(1);


  a2sum7 <= inputconv7 - a2mul7;

  a1sum7 <= a2sum7 - a3mul7;

  b2sum7 <= b1mul7 + b2mul7;

  b1sum7 <= b2sum7 + b3mul7;

  scale8 <= b1sum7 * scaleconst8;

  scaletypeconvert8 <= scale8;


  --   ------------------ Section 8 ------------------

  delay_process_section8 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section8(0) <= 0.0000000000000000E+00;
      delay_section8(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section8(1) <= delay_section8(0);
        delay_section8(0) <= a1sum8;
      END IF;
    END IF;
  END PROCESS delay_process_section8;

  inputconv8 <= scaletypeconvert8;


  a2mul8 <= delay_section8(0) * coeff_a2_section8;

  a3mul8 <= delay_section8(1) * coeff_a3_section8;

  b1mul8 <= a1sum8;


  b2mul8 <= delay_section8(0) * coeff_b2_section8;

  b3mul8 <= delay_section8(1);


  a2sum8 <= inputconv8 - a2mul8;

  a1sum8 <= a2sum8 - a3mul8;

  b2sum8 <= b1mul8 + b2mul8;

  b1sum8 <= b2sum8 + b3mul8;

  scale9 <= b1sum8 * scaleconst9;

  scaletypeconvert9 <= scale9;


  --   ------------------ Section 9 ------------------

  delay_process_section9 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section9(0) <= 0.0000000000000000E+00;
      delay_section9(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section9(1) <= delay_section9(0);
        delay_section9(0) <= a1sum9;
      END IF;
    END IF;
  END PROCESS delay_process_section9;

  inputconv9 <= scaletypeconvert9;


  a2mul9 <= delay_section9(0) * coeff_a2_section9;

  a3mul9 <= delay_section9(1) * coeff_a3_section9;

  b1mul9 <= a1sum9;


  b2mul9 <= delay_section9(0) * coeff_b2_section9;

  b3mul9 <= delay_section9(1);


  a2sum9 <= inputconv9 - a2mul9;

  a1sum9 <= a2sum9 - a3mul9;

  b2sum9 <= b1mul9 + b2mul9;

  b1sum9 <= b2sum9 + b3mul9;

  scale10 <= b1sum9 * scaleconst10;

  scaletypeconvert10 <= scale10;


  --   ------------------ Section 10 ------------------

  delay_process_section10 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section10(0) <= 0.0000000000000000E+00;
      delay_section10(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section10(1) <= delay_section10(0);
        delay_section10(0) <= a1sum10;
      END IF;
    END IF;
  END PROCESS delay_process_section10;

  inputconv10 <= scaletypeconvert10;


  a2mul10 <= delay_section10(0) * coeff_a2_section10;

  a3mul10 <= delay_section10(1) * coeff_a3_section10;

  b1mul10 <= a1sum10;


  b2mul10 <= delay_section10(0) * coeff_b2_section10;

  b3mul10 <= delay_section10(1);


  a2sum10 <= inputconv10 - a2mul10;

  a1sum10 <= a2sum10 - a3mul10;

  b2sum10 <= b1mul10 + b2mul10;

  b1sum10 <= b2sum10 + b3mul10;

  scale11 <= b1sum10 * scaleconst11;

  scaletypeconvert11 <= scale11;


  --   ------------------ Section 11 ------------------

  delay_process_section11 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section11(0) <= 0.0000000000000000E+00;
      delay_section11(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section11(1) <= delay_section11(0);
        delay_section11(0) <= a1sum11;
      END IF;
    END IF;
  END PROCESS delay_process_section11;

  inputconv11 <= scaletypeconvert11;


  a2mul11 <= delay_section11(0) * coeff_a2_section11;

  a3mul11 <= delay_section11(1) * coeff_a3_section11;

  b1mul11 <= a1sum11;


  b2mul11 <= delay_section11(0) * coeff_b2_section11;

  b3mul11 <= delay_section11(1);


  a2sum11 <= inputconv11 - a2mul11;

  a1sum11 <= a2sum11 - a3mul11;

  b2sum11 <= b1mul11 + b2mul11;

  b1sum11 <= b2sum11 + b3mul11;

  scale12 <= b1sum11 * scaleconst12;

  scaletypeconvert12 <= scale12;


  --   ------------------ Section 12 ------------------

  delay_process_section12 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section12(0) <= 0.0000000000000000E+00;
      delay_section12(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section12(1) <= delay_section12(0);
        delay_section12(0) <= a1sum12;
      END IF;
    END IF;
  END PROCESS delay_process_section12;

  inputconv12 <= scaletypeconvert12;


  a2mul12 <= delay_section12(0) * coeff_a2_section12;

  a3mul12 <= delay_section12(1) * coeff_a3_section12;

  b1mul12 <= a1sum12;


  b2mul12 <= delay_section12(0) * coeff_b2_section12;

  b3mul12 <= delay_section12(1);


  a2sum12 <= inputconv12 - a2mul12;

  a1sum12 <= a2sum12 - a3mul12;

  b2sum12 <= b1mul12 + b2mul12;

  b1sum12 <= b2sum12 + b3mul12;

  scale13 <= b1sum12 * scaleconst13;

  scaletypeconvert13 <= scale13;


  --   ------------------ Section 13 ------------------

  delay_process_section13 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section13(0) <= 0.0000000000000000E+00;
      delay_section13(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section13(1) <= delay_section13(0);
        delay_section13(0) <= a1sum13;
      END IF;
    END IF;
  END PROCESS delay_process_section13;

  inputconv13 <= scaletypeconvert13;


  a2mul13 <= delay_section13(0) * coeff_a2_section13;

  a3mul13 <= delay_section13(1) * coeff_a3_section13;

  b1mul13 <= a1sum13;


  b2mul13 <= delay_section13(0) * coeff_b2_section13;

  b3mul13 <= delay_section13(1);


  a2sum13 <= inputconv13 - a2mul13;

  a1sum13 <= a2sum13 - a3mul13;

  b2sum13 <= b1mul13 + b2mul13;

  b1sum13 <= b2sum13 + b3mul13;

  scale14 <= b1sum13 * scaleconst14;

  scaletypeconvert14 <= scale14;


  --   ------------------ Section 14 ------------------

  delay_process_section14 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section14(0) <= 0.0000000000000000E+00;
      delay_section14(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section14(1) <= delay_section14(0);
        delay_section14(0) <= a1sum14;
      END IF;
    END IF;
  END PROCESS delay_process_section14;

  inputconv14 <= scaletypeconvert14;


  a2mul14 <= delay_section14(0) * coeff_a2_section14;

  a3mul14 <= delay_section14(1) * coeff_a3_section14;

  b1mul14 <= a1sum14;


  b2mul14 <= delay_section14(0) * coeff_b2_section14;

  b3mul14 <= delay_section14(1);


  a2sum14 <= inputconv14 - a2mul14;

  a1sum14 <= a2sum14 - a3mul14;

  b2sum14 <= b1mul14 + b2mul14;

  b1sum14 <= b2sum14 + b3mul14;

  scale15 <= b1sum14 * scaleconst15;

  scaletypeconvert15 <= scale15;


  --   ------------------ Section 15 ------------------

  delay_process_section15 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section15(0) <= 0.0000000000000000E+00;
      delay_section15(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section15(1) <= delay_section15(0);
        delay_section15(0) <= a1sum15;
      END IF;
    END IF;
  END PROCESS delay_process_section15;

  inputconv15 <= scaletypeconvert15;


  a2mul15 <= delay_section15(0) * coeff_a2_section15;

  a3mul15 <= delay_section15(1) * coeff_a3_section15;

  b1mul15 <= a1sum15;


  b2mul15 <= delay_section15(0) * coeff_b2_section15;

  b3mul15 <= delay_section15(1);


  a2sum15 <= inputconv15 - a2mul15;

  a1sum15 <= a2sum15 - a3mul15;

  b2sum15 <= b1mul15 + b2mul15;

  b1sum15 <= b2sum15 + b3mul15;

  scale16 <= b1sum15 * scaleconst16;

  scaletypeconvert16 <= scale16;


  --   ------------------ Section 16 ------------------

  delay_process_section16 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section16(0) <= 0.0000000000000000E+00;
      delay_section16(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section16(1) <= delay_section16(0);
        delay_section16(0) <= a1sum16;
      END IF;
    END IF;
  END PROCESS delay_process_section16;

  inputconv16 <= scaletypeconvert16;


  a2mul16 <= delay_section16(0) * coeff_a2_section16;

  a3mul16 <= delay_section16(1) * coeff_a3_section16;

  b1mul16 <= a1sum16;


  b2mul16 <= delay_section16(0) * coeff_b2_section16;

  b3mul16 <= delay_section16(1);


  a2sum16 <= inputconv16 - a2mul16;

  a1sum16 <= a2sum16 - a3mul16;

  b2sum16 <= b1mul16 + b2mul16;

  b1sum16 <= b2sum16 + b3mul16;

  scale17 <= b1sum16 * scaleconst17;

  scaletypeconvert17 <= scale17;


  --   ------------------ Section 17 ------------------

  delay_process_section17 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section17(0) <= 0.0000000000000000E+00;
      delay_section17(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section17(1) <= delay_section17(0);
        delay_section17(0) <= a1sum17;
      END IF;
    END IF;
  END PROCESS delay_process_section17;

  inputconv17 <= scaletypeconvert17;


  a2mul17 <= delay_section17(0) * coeff_a2_section17;

  a3mul17 <= delay_section17(1) * coeff_a3_section17;

  b1mul17 <= a1sum17;


  b2mul17 <= delay_section17(0) * coeff_b2_section17;

  b3mul17 <= delay_section17(1);


  a2sum17 <= inputconv17 - a2mul17;

  a1sum17 <= a2sum17 - a3mul17;

  b2sum17 <= b1mul17 + b2mul17;

  b1sum17 <= b2sum17 + b3mul17;

  scale18 <= b1sum17 * scaleconst18;

  scaletypeconvert18 <= scale18;


  --   ------------------ Section 18 (First Order) ------------------

  delay_process_section18 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section18 <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section18 <= a1sum18;
      END IF;
    END IF; 
  END PROCESS delay_process_section18;

  inputconv18 <= scaletypeconvert18;


  a2mul18 <= delay_section18 * coeff_a2_section18;

  b1mul18 <= a1sum18;


  b2mul18 <= delay_section18;


  a1sum18 <= inputconv18 - a2mul18;

  b1sum18 <= b1mul18 + b2mul18;

  output_typeconvert <= b1sum18;


  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= output_register;
END rtl;
