-- -------------------------------------------------------------
--
-- Module: butterworth_10MHz_tb_pkg
-- Generated by MATLAB(R) 8.1 and the Filter Design HDL Coder 2.9.3.
-- Generated on: 2013-09-06 14:26:08
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- TargetDirectory: /home/MQCO/matlab_iirFilter
-- Name: butterworth_10MHz
-- TestBenchName: butterworth_10MHz_tb
-- TestBenchStimulus: impulse step 
--
-- Filter Settings:
--
-- Filter Specifications:
-- Sampling Frequency : N/A (normalized frequency)
-- Response           : Lowpass
-- Specification      : N,F3dB
-- Filter Order       : 5
-- 3-dB Point         : 0.2
--
-- Discrete-Time IIR Filter (real)
-- -------------------------------
-- Filter Structure    : Direct-Form II, Second-Order Sections
-- Number of Sections  : 3
-- Stable              : Yes
-- Linear Phase        : No
-- Arithmetic          : fixed
-- Numerator           : s16,13 -> [-4 4)
-- Denominator         : s16,14 -> [-2 2)
-- Scale Values        : s16,17 -> [-2.500000e-01 2.500000e-01)
-- Input               : s16,15 -> [-1 1)
-- Section Input       : s16,11 -> [-16 16)
-- Section Output      : s16,10 -> [-32 32)
-- Output              : s16,10 -> [-32 32)
-- State               : s16,15 -> [-1 1)
-- Numerator Prod      : s32,28 -> [-8 8)
-- Denominator Prod    : s32,29 -> [-4 4)
-- Numerator Accum     : s40,28 -> [-2048 2048)
-- Denominator Accum   : s40,29 -> [-1024 1024)
-- Round Mode          : convergent
-- Overflow Mode       : wrap
-- Cast Before Sum     : true
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;


PACKAGE butterworth_10MHz_tb_pkg IS

  -- Type Definitions
  TYPE filter_in_data_log_type IS ARRAY (0 TO 211) OF std_logic_vector(15 DOWNTO 0);

  -- Constants

  -- Functions
  FUNCTION to_integer( x : IN std_logic) RETURN integer;
  FUNCTION to_hex( x : IN std_logic) RETURN string;
  FUNCTION to_hex( x : IN std_logic_vector) RETURN string;
  FUNCTION to_hex( x : IN bit_vector ) RETURN string;
  FUNCTION to_hex( x : IN signed ) RETURN string;
  FUNCTION to_hex( x : IN unsigned ) RETURN string;
  FUNCTION to_hex( x : IN real ) RETURN string;
  FUNCTION SLICE( x : IN bit_vector; slice : In Integer) RETURN std_logic_vector;
  FUNCTION SLICE( x : IN bit_vector; slice : In Integer) RETURN signed;
  FUNCTION SLICE( x : IN bit_vector; slice : In Integer) RETURN unsigned;

  -- Procedures
  PROCEDURE filter_in_data_log_procedure 
    (SIGNAL clk      : IN    std_logic;
     SIGNAL reset    : IN    std_logic;
     SIGNAL rdenb    : IN    std_logic;
     SIGNAL addr     : INOUT unsigned(7 DOWNTO 0);
     SIGNAL done     : OUT   std_logic);

  PROCEDURE filter_out_procedure 
    (SIGNAL clk      : IN    std_logic;
     SIGNAL reset    : IN    std_logic;
     SIGNAL rdenb    : IN    std_logic;
     SIGNAL addr     : INOUT unsigned(7 DOWNTO 0);
     SIGNAL done     : OUT   std_logic);

END butterworth_10MHz_tb_pkg;

PACKAGE BODY butterworth_10MHz_tb_pkg IS
  FUNCTION to_integer( x : IN std_logic) RETURN integer IS
    VARIABLE int: integer;
  BEGIN
    IF x = '0' THEN
      int := 0;
    ELSE
      int := 1;
    END IF;
    RETURN int;
  END;

  FUNCTION to_hex( x : IN std_logic_vector) RETURN string IS
    VARIABLE result  : STRING(1 TO 256); -- 1024 bits max
    VARIABLE i       : INTEGER;
    VARIABLE imod    : INTEGER;
    VARIABLE j       : INTEGER;
    VARIABLE jinc    : INTEGER;
    VARIABLE newx    : std_logic_vector(1023 DOWNTO 0);
  BEGIN
    newx := (OTHERS => '0');
    IF x'LEFT > x'RIGHT THEN
      j := x'LENGTH-1;
      jinc := -1;
    ELSE
      j := 0;
      jinc := 1;
    END IF;
    FOR i IN x'RANGE LOOP
      newx(j) := x(i);
      j := j+jinc;
    END LOOP;  -- i
    i := x'LENGTH-1;
    imod := x'LENGTH MOD 4;
    IF    imod = 1 THEN i := i+3;
    ELSIF imod = 2 THEN i := i+2;
    ELSIF imod = 3 THEN i := i+1;
    END IF;
    j := 1;
    WHILE i >= 3 LOOP
      IF    newx(i DOWNTO (i-3)) = "0000" THEN result(j) := '0';
      ELSIF newx(i DOWNTO (i-3)) = "0001" THEN result(j) := '1';
      ELSIF newx(i DOWNTO (i-3)) = "0010" THEN result(j) := '2';
      ELSIF newx(i DOWNTO (i-3)) = "0011" THEN result(j) := '3';
      ELSIF newx(i DOWNTO (i-3)) = "0100" THEN result(j) := '4';
      ELSIF newx(i DOWNTO (i-3)) = "0101" THEN result(j) := '5';
      ELSIF newx(i DOWNTO (i-3)) = "0110" THEN result(j) := '6';
      ELSIF newx(i DOWNTO (i-3)) = "0111" THEN result(j) := '7';
      ELSIF newx(i DOWNTO (i-3)) = "1000" THEN result(j) := '8';
      ELSIF newx(i DOWNTO (i-3)) = "1001" THEN result(j) := '9';
      ELSIF newx(i DOWNTO (i-3)) = "1010" THEN result(j) := 'A';
      ELSIF newx(i DOWNTO (i-3)) = "1011" THEN result(j) := 'B';
      ELSIF newx(i DOWNTO (i-3)) = "1100" THEN result(j) := 'C';
      ELSIF newx(i DOWNTO (i-3)) = "1101" THEN result(j) := 'D';
      ELSIF newx(i DOWNTO (i-3)) = "1110" THEN result(j) := 'E';
      ELSIF newx(i DOWNTO (i-3)) = "1111" THEN result(j) := 'F';
      ELSE result(j) := 'X';
      END IF;
      i := i-4;
      j := j+1;
    END LOOP;
    RETURN result(1 TO j-1);
  END;


  FUNCTION to_hex( x : IN std_logic ) RETURN string IS
  BEGIN
    RETURN std_logic'image(x);
  END;


  FUNCTION to_hex( x : IN bit_vector ) RETURN string IS
  BEGIN
    RETURN to_hex( to_stdlogicvector(x) );
  END;


  FUNCTION to_hex( x : IN signed ) RETURN string IS
  BEGIN
    RETURN to_hex( std_logic_vector(x) );
  END;


  FUNCTION to_hex( x : IN unsigned ) RETURN string IS
  BEGIN
    RETURN to_hex( std_logic_vector(x) );
  END;


  FUNCTION to_hex( x : IN real ) RETURN string IS
  BEGIN
    RETURN real'image(x);
  END;


  FUNCTION SLICE( x : IN bit_vector; slice : IN Integer) RETURN std_logic_vector IS
    variable result : std_logic_vector(slice - 1 DOWNTO 0);
  BEGIN
    result := to_stdlogicvector(bit_vector'(x))(slice - 1 DOWNTO 0);
    RETURN result;
  END;


  FUNCTION SLICE( x : IN bit_vector; slice : IN Integer) RETURN signed IS
    variable result : signed(slice -  1 DOWNTO 0);
  BEGIN
    result := signed(to_stdlogicvector(bit_vector'(x))(slice - 1 DOWNTO 0));
    RETURN result;
  END;


  FUNCTION SLICE( x : IN bit_vector; slice : IN Integer) RETURN unsigned IS
    variable result : unsigned(slice -  1 DOWNTO 0);
  BEGIN
    result := unsigned(to_stdlogicvector(bit_vector'(x))(slice - 1 DOWNTO 0));
    RETURN result;
  END;


  PROCEDURE filter_in_data_log_procedure 
    (SIGNAL clk      : IN    std_logic;
     SIGNAL reset    : IN    std_logic;
     SIGNAL rdenb    : IN    std_logic;
     SIGNAL addr     : INOUT unsigned(7 DOWNTO 0);
     SIGNAL done     : OUT   std_logic) IS
  BEGIN
-- Counter to generate Addr.
    IF reset  = '1' THEN
      addr     <= TO_UNSIGNED(0,8);
    ELSIF clk'event and clk = '1' THEN
      IF rdenb = '1' THEN
        IF (addr = TO_UNSIGNED(211, 8 )) THEN
          addr     <= addr; 
        ELSE
          addr     <= addr + TO_UNSIGNED(1,8); 
        END IF;
      ELSE 
        addr <= addr;
      END IF;
    END IF;

-- Done Signal generation.
    IF reset  = '1' THEN
      done <= '0'; 
    ELSIF (addr = TO_UNSIGNED(211, 8 )) THEN
      done <= '1'; 
    ELSE
      done <= '0'; 
    END IF;
  END filter_in_data_log_procedure;

  PROCEDURE filter_out_procedure 
    (SIGNAL clk      : IN    std_logic;
     SIGNAL reset    : IN    std_logic;
     SIGNAL rdenb    : IN    std_logic;
     SIGNAL addr     : INOUT unsigned(7 DOWNTO 0);
     SIGNAL done     : OUT   std_logic) IS
  BEGIN
-- Counter to generate Addr.
    IF reset  = '1' THEN
      addr     <= TO_UNSIGNED(0,8);
    ELSIF clk'event and clk = '1' THEN
      IF rdenb = '1' THEN
        IF (addr = TO_UNSIGNED(211, 8 )) THEN
          addr     <= addr; 
        ELSE
          addr     <= addr + TO_UNSIGNED(1,8); 
        END IF;
      ELSE 
        addr <= addr;
      END IF;
    END IF;

-- Done Signal generation.
    IF reset  = '1' THEN
      done <= '0'; 
    ELSIF (addr = TO_UNSIGNED(211, 8 )) THEN
      done <= '1'; 
    ELSE
      done <= '0'; 
    END IF;
  END filter_out_procedure;

END butterworth_10MHz_tb_pkg;

-- -------------------------------------------------------------
--
-- Module: butterworth_10MHz_tb_data
-- Generated by MATLAB(R) 8.1 and the Filter Design HDL Coder 2.9.3.
-- Generated on: 2013-09-06 14:26:08
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;
USE work.butterworth_10MHz_tb_pkg.ALL;

PACKAGE butterworth_10MHz_tb_data IS

  CONSTANT filter_in_data_log_force : filter_in_data_log_type;
  CONSTANT filter_out_expected : filter_in_data_log_type;

END butterworth_10MHz_tb_data;

PACKAGE BODY butterworth_10MHz_tb_data IS

  CONSTANT filter_in_data_log_force : filter_in_data_log_type :=
    (
         X"7fff",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"7fff",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000");

  CONSTANT filter_out_expected : filter_in_data_log_type :=
    (
         X"0002",
         X"000b",
         X"0027",
         X"005e",
         X"00a1",
         X"00d7",
         X"00e7",
         X"00cb",
         X"008d",
         X"0041",
         X"fffd",
         X"ffd2",
         X"ffc4",
         X"ffcd",
         X"ffe3",
         X"fffb",
         X"000d",
         X"0015",
         X"0013",
         X"000c",
         X"0003",
         X"fffc",
         X"fff8",
         X"fff9",
         X"fffb",
         X"ffff",
         X"0002",
         X"0003",
         X"0003",
         X"0002",
         X"0001",
         X"0001",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0002",
         X"000c",
         X"0034",
         X"0091",
         X"0132",
         X"0207",
         X"02ee",
         X"03b9",
         X"0446",
         X"0488",
         X"0486",
         X"0459",
         X"041e",
         X"03eb",
         X"03cf",
         X"03cb",
         X"03d9",
         X"03ee",
         X"0402",
         X"040e",
         X"0411",
         X"040c",
         X"0403",
         X"03fb",
         X"03f6",
         X"03f4",
         X"03f6",
         X"03fa",
         X"03fd",
         X"03ff",
         X"0400",
         X"03ff",
         X"03fe",
         X"03fd",
         X"03fc",
         X"03fc",
         X"03fc",
         X"03fc",
         X"03fb",
         X"03fb",
         X"03fb",
         X"03fb",
         X"03fb",
         X"03fb",
         X"03fb",
         X"03fb",
         X"03fb",
         X"03fb",
         X"03fb",
         X"03fb",
         X"03fb",
         X"03fb",
         X"03fa",
         X"03f0",
         X"03c9",
         X"036c",
         X"02cc",
         X"01f7",
         X"0110",
         X"0044",
         X"ffb7",
         X"ff76",
         X"ff78",
         X"ffa5",
         X"ffe0",
         X"0012",
         X"002e",
         X"0032",
         X"0024",
         X"000e",
         X"fffb",
         X"ffef",
         X"ffec",
         X"fff0",
         X"fff9",
         X"0002",
         X"0008",
         X"000a",
         X"0007",
         X"0004",
         X"0000",
         X"fffe",
         X"fffd",
         X"fffd",
         X"fffe",
         X"ffff",
         X"ffff",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000",
         X"0000");

END butterworth_10MHz_tb_data;
-- -------------------------------------------------------------
--
-- Module: butterworth_10MHz_tb
-- Generated by MATLAB(R) 8.1 and the Filter Design HDL Coder 2.9.3.
-- Generated on: 2013-09-06 14:26:08
-- -------------------------------------------------------------

-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

USE work.butterworth_10MHz_tb_pkg.ALL;

USE work.butterworth_10MHz_tb_data.ALL;

ENTITY butterworth_10MHz_tb IS

END butterworth_10MHz_tb;


ARCHITECTURE rtl OF butterworth_10MHz_tb IS
  -- -------------------------------------------------------------
  -- Component Declarations
  -- -------------------------------------------------------------
  COMPONENT butterworth_10MHz
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(15 DOWNTO 0); -- sfix16_En15
         filter_out                      :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En10
         );
  END COMPONENT;

  -- -------------------------------------------------------------
  -- Component Configuration Statements
  -- -------------------------------------------------------------
  FOR ALL : butterworth_10MHz
    USE ENTITY work.butterworth_10MHz(rtl);

  -- Constants
  CONSTANT clk_high                         : time := 5 ns;
  CONSTANT clk_low                          : time := 5 ns;
  CONSTANT clk_period                       : time := 10 ns;
  CONSTANT clk_hold                         : time := 2 ns;
  CONSTANT MAX_TIMEOUT                    : integer := 3; -- uint32
  CONSTANT MAX_ERROR_COUNT                : integer := 212; -- uint32


  -- Signals
  SIGNAL clk                              : std_logic; -- boolean
  SIGNAL clk_enable                       : std_logic; -- boolean
  SIGNAL reset                            : std_logic; -- boolean
  SIGNAL filter_in                        : std_logic_vector(15 DOWNTO 0); -- sfix16_En15
  SIGNAL filter_out                       : std_logic_vector(15 DOWNTO 0); -- sfix16_En10

  SIGNAL tb_enb                           : std_logic; -- boolean
  SIGNAL srcDone                          : std_logic; -- boolean
  SIGNAL snkDone                          : std_logic; -- boolean
  SIGNAL testFailure                      : std_logic; -- boolean
  SIGNAL tbenb_dly                        : std_logic; -- boolean
  SIGNAL rdEnb                            : std_logic; -- boolean
  SIGNAL filter_in_data_log_rdenb         : std_logic; -- boolean
  SIGNAL filter_in_data_log_addr          : unsigned(7 DOWNTO 0); -- ufix8
  SIGNAL filter_in_data_log_done          : std_logic; -- boolean
  SIGNAL filter_out_testFailure           : std_logic; -- boolean
  SIGNAL filter_out_timeout               : integer; -- uint32
  SIGNAL filter_out_errCnt                : integer; -- uint32
  SIGNAL delayLine_out                    : std_logic; -- boolean
  SIGNAL expected_ce_out                  : std_logic; -- boolean
  SIGNAL int_delay_pipe                   : std_logic_vector(0 TO 1); -- boolean
  SIGNAL filter_out_rdenb                 : std_logic; -- boolean
  SIGNAL filter_out_addr                  : unsigned(7 DOWNTO 0); -- ufix8
  SIGNAL filter_out_done                  : std_logic; -- boolean
  SIGNAL filter_out_ref                   : std_logic_vector(15 DOWNTO 0); -- sfix16_En10
  SIGNAL check1_Done                      : std_logic; -- boolean


BEGIN
  -- Component Instances
  u_butterworth_10MHz: butterworth_10MHz
    PORT MAP (
              clk                              => clk,
              clk_enable                       => clk_enable,
              reset                            => reset,
              filter_in                        => filter_in,
              filter_out                       => filter_out      );


  -- Block Statements
  -- -------------------------------------------------------------
  -- Driving the test bench enable
  -- -------------------------------------------------------------

  tb_enb <= '0' WHEN reset = '1' ELSE 
            '1' WHEN snkDone = '0' ELSE 
            '0' AFTER clk_period * 2;

  completed_msg: PROCESS (clk, reset)
  BEGIN
    IF (reset = '1') THEN 
       -- Nothing to reset here.
    ELSIF clk'event AND clk = '1' THEN
      IF snkDone='1' THEN
        IF (testFailure = '0') THEN
              ASSERT FALSE
                REPORT "**************TEST COMPLETED (PASSED)**************"
                SEVERITY NOTE;
        ELSE
              ASSERT FALSE
                REPORT "**************TEST COMPLETED (FAILED)**************"
                SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

  -- -------------------------------------------------------------
  -- System Clock (fast clock) and reset
  -- -------------------------------------------------------------

  clk_gen: PROCESS
  BEGIN
    clk <= '1';
    WAIT FOR clk_high;
    clk <= '0';
    WAIT FOR clk_low;
    IF snkDone = '1' THEN
      clk <= '1';
      WAIT FOR clk_high;
      clk <= '0';
      WAIT FOR clk_low;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  reset_gen: PROCESS
  BEGIN
    reset <= '1';
    WAIT FOR clk_period * 2;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR clk_hold;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  -- -------------------------------------------------------------
  -- Testbench clock enable
  -- -------------------------------------------------------------

  tb_enb_delay : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tbenb_dly <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF tb_enb = '1' THEN
        tbenb_dly <= tb_enb;
      END IF;
    END IF; 
  END PROCESS tb_enb_delay;

  rdEnb <= tbenb_dly WHEN snkDone =  '0' ELSE
           '0';

  -- -------------------------------------------------------------
  -- Read the data and transmit it to the DUT
  -- -------------------------------------------------------------

  filter_in_data_log_procedure (
    clk       => clk,
    reset     => reset,
    rdenb     => filter_in_data_log_rdenb,
    addr      => filter_in_data_log_addr,
    done      => filter_in_data_log_done);

  filter_in_data_log_rdenb <= rdEnb;

  stimuli_filter_in_data_log : PROCESS(filter_in_data_log_addr, filter_in_data_log_rdenb)
  BEGIN
    IF filter_in_data_log_rdenb = '1' THEN
      filter_in <= filter_in_data_log_force(TO_INTEGER(filter_in_data_log_addr)) AFTER clk_hold;
    END IF;
  END PROCESS stimuli_filter_in_data_log;

  -- -------------------------------------------------------------
  -- Create done signal for Input data
  -- -------------------------------------------------------------

  srcDone <= filter_in_data_log_done;


  ceout_delayLine : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      int_delay_pipe(0 TO 1) <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN 
      IF clk_enable = '1' THEN
        int_delay_pipe(0) <= rdEnb;
        int_delay_pipe(1) <= int_delay_pipe(0);
      END IF;
    END IF; 
  END PROCESS ceout_delayLine;

  delayLine_out <= int_delay_pipe(1);

  expected_ce_out <=  delayLine_out AND clk_enable;

  -- -------------------------------------------------------------
  --  Checker: Checking the data received from the DUT.
  -- -------------------------------------------------------------

  filter_out_procedure (
    clk       => clk,
    reset     => reset,
    rdenb     => filter_out_rdenb,
    addr      => filter_out_addr,
    done      => filter_out_done);

  filter_out_rdenb <= expected_ce_out;

  filter_out_ref <= filter_out_expected(TO_INTEGER(filter_out_addr));
  checker_1: PROCESS(clk, reset)
  BEGIN
    IF reset = '1' THEN
      filter_out_timeout <= 0;
      filter_out_errCnt <= 0;
      filter_out_testFailure <= '0';
    ELSIF clk'event and clk ='1' THEN
      IF filter_out_rdenb = '1' THEN
        filter_out_timeout <= 0;
        IF filter_out /= filter_out_expected(TO_INTEGER(filter_out_addr)) THEN
          filter_out_errCnt <= filter_out_errCnt + 1;
          filter_out_testFailure <= '1';
          ASSERT FALSE 
            REPORT "Error in filter_out: Expected " 
            & to_hex(filter_out_expected(TO_INTEGER(filter_out_addr)))
            & " Actual "
            & to_hex(filter_out)
            SEVERITY ERROR;
          IF filter_out_errCnt >= MAX_ERROR_COUNT THEN
            ASSERT FALSE
              REPORT "Number of errors have exceeded the maximum error"
              SEVERITY Warning;
          END IF;
        END IF;
      ELSIF filter_out_timeout > MAX_TIMEOUT AND filter_out_rdenb = '1' THEN
        filter_out_errCnt <= filter_out_errCnt + 1;
        filter_out_testFailure <= '1';
        ASSERT FALSE
          REPORT "Timeout: Data was not received after timeout."
          SEVERITY FAILURE ;
      ELSIF filter_out_rdenb = '1' THEN
        filter_out_timeout <= filter_out_timeout + 1 ;
      END IF;
    END IF;
  END PROCESS checker_1;

  checkDone_1: PROCESS(clk, reset)
  BEGIN
    IF reset = '1' THEN
      check1_Done <= '0';
    ELSIF clk'event and clk ='1' THEN
      IF check1_Done = '0' AND filter_out_done = '1' AND filter_out_rdenb = '1' THEN
        check1_Done <= '1';
      END IF;
    END IF;
  END PROCESS checkDone_1;
  -- -------------------------------------------------------------
  -- Create done and test failure signal for output data
  -- -------------------------------------------------------------

  snkDone <= check1_Done;

  testFailure <= filter_out_testFailure;

  -- -------------------------------------------------------------
  -- Global clock enable
  -- -------------------------------------------------------------
  clk_enable <= tbenb_dly AFTER clk_hold WHEN snkDone = '0' ELSE
                '0' AFTER clk_hold;

  -- Assignment Statements



END rtl;
